version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: "start-dev"
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/bin/keycloak_export_dir/realm-export.json
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/demo/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/demo/certs/key.pem
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./keycloak-config/data-transfer-application-keycloak-config.json:/opt/jboss/keycloak/bin/keycloak_export_dir/data-transfer-application-keycloak-config.json"
      - ./certs:/opt/keycloak/demo/certs

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontendwithkeyCloak/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontendwithkeyCloak/dataTransferApplication

  database:
    image: postgres:latest
    container_name: "database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1811786
      POSTGRES_DB: exceldata2
    ports:
      - "5430:5432"

  backend:
    build:
      context: .
      dockerfile: backendWithkeyCloak/Dockerfile
    container_name: "backend"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/exceldata2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1811786
    ports:
      - "8081:8081"
    volumes:
      - ./certs:/app/certs
    depends_on:
      - database
